---
location_data:
    input_path: './roadscene2vec_pkls/271_carla_image_dataset_10_frame_128x72.pkl' #path to pkl containing real image dataset training/testing data
    transfer_path: null #path to transfer dataset for transfer learning
    
model_config:
  model: 'cnn_lstm' 
  load_model: False #load pretrained model
  model_load_path: null #path to load pretrained model
  model_save_path: null #path to save trained model
  dropout: 0.1 #dropout probability
  nclass: 2 #dimension of final output
  device: 'cuda' #device to place training/testing data batches
  bnorm: True #enable or disable batch normalization. implemented only for cnn_lstm model
  
training_config:
  dataset_type: "real" #type of training/testing data. Options: real, scenegraph
  task_type: 'sequence_classification' #Task options. Options: sequence_classification, graph_classification, collision_prediction
  n_fold: 1 #number of folds for n-fold cross validation
  learning_rate: 0.0001 
  epochs: 500
  split_ratio: 0.3 #train-test split ratio
  downsample: False
  seed: 0 #seed used for train-test split
  batch_size: 32 #batch size of training, testing data
  test_step: 10 #perform test validation every n epochs
  weight_decay: 0.0005
  
wandb_config:
  entity: '<fill in your username here>'
  project: '<fill in your project name here>'
